title : Gayeon Lee
logo : https://github.com/glee255/glee255/blob/main/assets/Lee_Gayeon%20-01-GradSch2025-retouched.jpg
#description : text below image
#show_downloads : true
theme : jekyll-theme-minimal
